---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: [name]
spec:
  replicas: 12
  selector:
    matchLabels:
      app: [name]
  template:
    metadata:
      labels:
        app: [name]
    spec:
      containers:
        - command:
            - /usr/bin/tf_serving_entrypoint.sh
            - --model_config_file=[model]
          name: [name]
          image: [repo]/[image]
          ports:
            - containerPort: 8500
