apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-minimize-sch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-minimize-sch
  template:
    metadata:
      labels:
        app: test-minimize-sch
      spec:
        schedulerName: wao-scheduler
        containers:
          - name: test-minimize-scheduler
            image: httpd:latest
            resources:
              requests:
                cpu: "1"
              limits:
                cpu: "0.5"
