---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: wao-scheduler
  namespace: kube-system
spec:
  serviceAccountName: wao-scheduler
  containers:
    - name: wao-scheduler
      command:
        - kube-scheduler
        - --bind-address=127.0.0.1
        - --leader-elect=false
        - --config=/config-volume/kube-scheduler-configuration.yaml
        - --v=5
      image: [repository-address]/[image-name]
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 15
      resources:
        requests:
          cpu: 2
      startupProbe:
        failureThreshold: 24
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 15
      volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /config-volume
          name: kubeschedulerconfig
          readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
    - hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: FileOrCreate
      name: kubeconfig
    - configMap:
        name: kubeschedulerconfig-cm
      name: kubeschedulerconfig
